import { api } from "@/api/client";

interface RunData {
  outcome: string | null;
  floor_count: number;
  floors_completed: number;
  starting_level: number;
  total_gold_earned: number;
  total_shards_earned: number;
  armillary_favour: number;
  seed: number;
  started_at: string;
}

interface MetaData {
  essence_earned: number;
  new_achievements: { name: string; description: string }[];
  lore_fragments_discovered: { title: string; text: string }[];
}

/**
 * Compile run data into a markdown summary for copying/exporting.
 */
export function generateSessionMarkdown(
  run: RunData,
  meta?: MetaData | null,
): string {
  const isVictory = run.outcome === "completed";
  const lines: string[] = [];

  lines.push(`# Drifting Infinity — Session Summary`);
  lines.push("");
  lines.push(`**Result:** ${isVictory ? "Victory" : "Defeat"}`);
  lines.push(`**Floors:** ${run.floors_completed} / ${run.floor_count}`);
  lines.push(`**Starting Level:** ${run.starting_level}`);

  const start = new Date(run.started_at);
  lines.push(`**Date:** ${start.toLocaleDateString()} ${start.toLocaleTimeString()}`);
  lines.push(`**Seed:** ${run.seed}`);

  lines.push("");
  lines.push("## Earnings");
  lines.push(`- Gold: ${run.total_gold_earned.toLocaleString()}`);
  lines.push(`- Astral Shards: ${run.total_shards_earned.toLocaleString()}`);
  lines.push(`- Armillary Favour: ${run.armillary_favour}`);

  if (meta) {
    lines.push(`- Essence: +${meta.essence_earned}`);

    if (meta.new_achievements.length > 0) {
      lines.push("");
      lines.push("## Achievements Unlocked");
      for (const a of meta.new_achievements) {
        lines.push(`- **${a.name}** — ${a.description}`);
      }
    }

    if (meta.lore_fragments_discovered.length > 0) {
      lines.push("");
      lines.push("## Lore Discovered");
      for (const f of meta.lore_fragments_discovered) {
        lines.push(`- **${f.title}** — ${f.text}`);
      }
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by Drifting Infinity*");

  return lines.join("\n");
}

/**
 * Copy text to clipboard and return success.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Server-side export API
// ---------------------------------------------------------------------------

export interface ExportOptions {
  format: "json" | "markdown";
}

/**
 * Export a full run from the backend.
 * Returns JSON data or markdown string depending on format.
 */
export async function exportRun(
  runId: string,
  options: ExportOptions = { format: "json" },
): Promise<string | Record<string, unknown>> {
  if (options.format === "markdown") {
    const res = await fetch(`/api/export/runs/${runId}?format=markdown`);
    if (!res.ok) throw new Error(`Export failed: ${res.status}`);
    return res.text();
  }
  return api.get<Record<string, unknown>>(`/export/runs/${runId}?format=json`);
}

/**
 * Export a floor prep as a printable mini-module.
 * Returns JSON data or markdown string depending on format.
 */
export async function exportFloorPrep(
  floorId: string,
  options: ExportOptions = { format: "json" },
): Promise<string | Record<string, unknown>> {
  if (options.format === "markdown") {
    const res = await fetch(`/api/export/prep/floor/${floorId}?format=markdown`);
    if (!res.ok) throw new Error(`Export failed: ${res.status}`);
    return res.text();
  }
  return api.get<Record<string, unknown>>(`/export/prep/floor/${floorId}?format=json`);
}

/**
 * Download content as a file.
 */
export function downloadAsFile(
  content: string,
  filename: string,
  mimeType = "text/markdown",
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
